name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

env:
  BINARY_NAME: iface-proxy

jobs:
  build:
    name: Build (macos)
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo build
        uses: Swatinem/rust-cache@v2

      - name: Build (macOS)
        run: cargo build --release --locked

      - name: Package archive (macOS)
        run: |
          mkdir -p dist
          BIN_PATH=target/release/${{ env.BINARY_NAME }}
          ARCHIVE_NAME=${{ env.BINARY_NAME }}-${{ github.ref_name }}-macos.tar.gz
          tar -C $(dirname "$BIN_PATH") -czf dist/$ARCHIVE_NAME $(basename "$BIN_PATH")


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}-${{ github.ref_name }}-macos
          path: dist/*

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}-${{ github.ref_name }}-macos
          path: dist

      - name: Generate checksums
        run: |
          cd dist
          sha256sum * > checksums.txt

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            dist/*


